dna = """TTCCGCCCAAGAAACGATACCACCTGCAATGGTTGGTTCCGCCCCACTAGAATACTGCAT
GCCGCCAGGATCCCCACATCCGTCTTTTAGTGCTGTGCCCTGCTCTGTATCTTAGGGCGG
GTTTTAAAATACCAGTTGGATCATCTCTTCCCCCCGCGATATATAATTGACATCTCAAAT
TATACTTCTACGGCAATGGTACGGTCCGCTGACATACTGGCAGTGGGAGTGCTCGTCCCA
TGAAAGCTCGGTAGCGCAACCAATAGCACGTCGAGTTAATGATACAACCGATGTCTCGGG
ACCGGAAGTTCCATCTCTCTCTGGCGCAACAGGTGTGATTTCCTCGGGTTAAAGCGATCC
AAACGGTAGTTCCCCGTAGCGCACGCAGTATATCTTCGCCGGCTTAAAACTAGTCTCTAT
ACTGTAACAGGGAGAGAAAGAATTGATGGTACAACATTCCGTGTTCGTATTTTGTATCGG
CGGGTTTAAGGACACGGAGAAAATAGCGAACATATCTGAACAGCGCTGTACTAGCGAATG
AAGGCTCGCCCTCCCACTTTGACCTGCGCCGTTCTTATAGACGACTGATGACAATTACTA
AAGAGTCCTTTACCGTATATTACTACATAAGCCGCCATTGCGTGCAAGCTGAGGCAGCAC
CCATACCCGAGCCCATAGAGGTATAAGTCCCCAGACGGTTAACAAGCGCGGGTGTCTCCG
TTCCCCACGGTGTGGCTAATCAAGTCACCTCGATAAATTAGCTTGCCAGCGAGAGGTCCG
TAACAGAGCAGTAGTTGTGGTATCAGACCCCTGCGTAACACGCGTCCTCGGCGAGTAACA
CAATCTCGTATGGTGGCACTGTATCCGGGTTGAGTAATACTATCTGTCGGAATAGGCTTC
GGGGGTCATGACAACCCGGCT"""
sp_motif = "ATACACCTCACTCTGGGCCTCGTCCACCCGTAGA" 

dna = dna.replace("\n","").replace(" ","")
positions = [] # To store toe positions
pos = 0 # To track where we are in dna 

for nuc in sp_motif:
    while dna[pos] != nuc: # move forward in dna until we find a match
        pos += 1
    positions.append(pos+1)
    pos += 1 # move to next position to continue search

print(*positions) # print each element in list separated by space
